name: PlotManager
version: '1.0'
main: ovinola.com.github.testePlotSquared.PlotManager
api-version: '1.8.8'
commands:
    plot:
        description: Comando para abrir menu gui da plot
        usage: /plot
    plotme:
        description: Comando para abrir menu gui da plot
        usage: /plotme
    p:
        description: Comando para abrir menu gui da plot
        usage: /p