name: TestePlotSquared
version: '1.0'
main: ovinola.com.github.testePlotSquared.TestePlotSquared
api-version: '1.8.8'
commands:
    plot:
        description: Comando para abrir menu gui da plot
        usage: /plot